### ISSUE TITLE
Sources lists only OTX user

### ISSUE THREAD

**Issue by jeffhammett** [hosom/bro-otx#1]
Would it be possible to include more info about the OTX pulse in the Sources field?

Currently when using this Bro script when I have an intel hit from OTX it only lists (what I think) is the OTX username that the indicator came from in the Sources field.

I was previously using the AlienVault Bro IDS Connector (https://github.com/AlienVault-Labs/OTX-Apps-Bro-IDS) but switched to this as it seemed like a better implementation. Using the AlienVault Bro IDS Connector the source in Bro's intel log was listed as "AlienVault OTX - [Pulse name] - [Pulse id]"

**Comment by hosom** [comment]
Jeff, 

I'll take a look tomorrow to see what I can do. Sorry for the silence on this.

**Comment by hosom** [comment]
Jeff,

I think the new format should fit your needs.

Let me know if you have feedback on it. 

Thanks, 

Stephen
