### ISSUE TITLE
Intel::URL entries need protocol removed

### ISSUE THREAD

**Issue by bruberg** [hosom/bro-otx#6]
In OTX, URLs are listed including the protocol scheme (`http://` `ftp://` etc). The `Intel::URL` indicator type (_seen.indicator_type_) in bro-otx fails to trigger if the scheme exists.

Example: if `otx.dat` has an `Intel::URL` entry "http://example.com/path.txt" Bro will not react. However, if the `otx.dat` entry is simply "example.com/path.txt", Bro triggers as expected.

Is it possible for bro-otx to strip the protocol scheme from `Intel::URL` types?

**Comment by hosom** [comment]
Yeah, there's an open pull request for this. I think that I can make this happen. In general this package needs some love. I'm going to try to get it updated into a bro package, so keep an eye out and I'll fix this too.

**Comment by hosom** [comment]
This should be resolved with 531cdcda218c82b303e99f83d7a7f7375ffa0d48, please let me know if you find any more issues.
